[alias]
lint = "clippy --all-targets --all-features"
test-all = "test --all-targets --all-features --no-fail-fast -- --test-threads=1"
audit = "clippy --all-targets --all-features -- -W clippy::cast_possible_truncation -W clippy::cast_sign_loss -W clippy::cast_possible_wrap -W clippy::cast_lossless -W clippy::checked_conversions -W clippy::redundant_clone -W clippy::fallible_impl_from"
